PREFIX :<http://www.ontotext.com/connectors/lucene#>
PREFIX inst:<http://www.ontotext.com/connectors/lucene/instance#>
INSERT DATA {
	inst:event-index :createConnector '''
{
  "fields": [
    {
      "fieldName": "name",
      "propertyChain": [
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": true,
      "facet": true
    },
    {
      "fieldName": "sameAs",
      "propertyChain": [
        "http://schema.org/sameAs"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": true,
      "facet": true
    },
    {
      "fieldName": "url",
      "propertyChain": [
        "http://schema.org/url"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": true,
      "facet": true
    },
    {
      "fieldName": "startDate",
      "propertyChain": [
        "http://schema.org/startDate"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": true,
      "facet": true
    },
    {
      "fieldName": "endDate",
      "propertyChain": [
        "http://schema.org/endDate"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": true,
      "facet": true
    },
    {
      "fieldName": "locationName",
      "propertyChain": [
        "http://schema.org/location",
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": true,
      "facet": true
    },
    {
      "fieldName": "locationPostalCode",
      "propertyChain": [
        "http://schema.org/location",
        "http://schema.org/address",
        "http://schema.org/postalCode"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": true,
      "facet": true
    }
  ],
  "languages": [],
  "types": [
    "http://schema.org/Event"
  ],
  "readonly": false,
  "detectFields": false,
  "importGraph": false,
  "skipInitialIndexing": false,
  "boostProperties": [],
  "stripMarkup": false
}
''' .
}