services:
  graphdb:
    image: ontotext/graphdb:10.6.3
    container_name: graphdb
    restart: always
    ports:
      - "7200:7200"
    command: >
      -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
      -Dgraphdb.workbench.cors.enable=true
      -Dgraphdb.home=/opt/graphdb/home
      -Xms2g
      -Xmx5g
      -XX:+UseG1GC
      -Dgraphdb.workbench.maxUploadSize=809715200
    volumes:
      - /home/ubuntu/graphdb/data:/opt/graphdb/home/data
      - /home/ubuntu/graphdb/import:/root/graphdb-import
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
volumes:
  graphdb-data:
  graphdb-import: